<?php

$lang = [

	'Homepage'=>'Hjemmeside',
	'Booking'=>'Booking',
	'Book help'=>'Book hjelp',
	'My bookings'=>'Mine bookinger',
	'Calendar'=>"Kalender",
	'Messages'=>'Meldinger',
	'Check bookings'=>'Sjekk bookinger',
	'Edit Calendar'=>'Rediger Kalender',
	'Welcome!'=>'Velkommen!',
    'General'=>'Generelt',
    'Assisant Teacher tools'=>'Hjelpelærer verktøy',
    'Profile'=>'Profil',
    'Logout'=>'Logg ut',
    'Settings'=>'Instillinger',
	'Show Calendar Entry'=>'Hvis kalender hendelse',
	'Title'=>'Tittel',
	'Description'=>'Beskrivelse',
	'Start time'=>'Start tid',
	'End time'=>'Slutt tid',
	'Close'=>'Lukk',
	'Assistant'=>'Hjelpelærer',
	'E-mail'=>'E-post',
	'View Profile'=>'Se profil',
	'Chat'=>'Prat',
	'No messages yet, Start the conversation'=>'Ingen meldinger ennå, Start en samtale',
	'exit'=>'lukk',
	'Edit Profile'=>'Rediger Profil',
	'Experience'=>'Erfaring',
	' Subjects'=>' Fag',
	'User Profile'=>'Bruker Profil',
	'Edit Password'=>'Rediger Passord',
	'Edit Courses'=>'Rediger Fag',
	'Edit profile information'=>'Rediger bruker informasjon',
	'Save changes'=>'Lagre Endringer',
	'Close'=>'Lukk',
	'Edit password'=>'Endre passord',
];

?>